process_mntoha:
  sequence_length: 400
  sequence_offset: 200
  spinup_time: 100
  source_dir: 1_fetch/out
  tmp_dir: 2_process/tmp
  out_dir: 2_process/out
  unzip_log_file: 2_process/log/unzipped_mntoha_files.txt
  metadata_file: 1_fetch/out/metadata_mntoha/lake_metadata.csv
  metadata_augmented_file: 2_process/tmp/metadata_mntoha/lake_metadata_augmented.csv
  obs_file: 2_process/tmp/obs_mntoha/temperature_observations/temperature_observations.csv
  obs_interpolated_file: 2_process/tmp/obs_mntoha/temperature_observations/temperature_observations_interpolated.csv
  depths: [0.0,  0.5,  1.0,  1.5,  2.0,  2.5,  3.0,  3.5,  4.0,  4.5,  5.0,
           5.5,  6.0,  6.5,  7.0,  7.5,  8.0,  8.5,  9.0,  9.5, 10.0, 11.0,
           12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 22.0, 24.0,
           26.0, 28.0, 30.0, 32.0, 34.0, 36.0, 38.0, 40.0, 45.0, 50.0, 55.0,
           60.0, 65.0, 70.0, 75.0, 80.]
